apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: connect-front
          image: registry.digitalocean.com/tvrnxr/connect-front:v5
          command: ["npm", "run", "preview"]
          ports:
            - containerPort: 4173
